### ISSUE TITLE
Zooming really slow?

### ISSUE THREAD

**Issue by JeremyRubin** [projectstorm/react-diagrams#516] opened 2020-01-08 03:40 UTC
First off, great project!

I've noticed that the zooming functionality is really slow in Firefox -- that is, the zoom-levels per scroll is really small, actual rendering is snappy. I'm not quite sure what's going on, but it makes it basically impossible to zoom in/out sufficiently.

Chrome is unaffected.

**Comment by lukethacoder** [comment] 2020-01-08 11:40
https://github.com/projectstorm/react-diagrams/issues/360

**Comment by renato-bohler** [comment] 2020-01-08 12:10
I this this (and #360) may be solved by adding a `zoomStep` option to `ZoomCanvasAction`.

The changes would look something like this: https://github.com/projectstorm/react-diagrams/compare/master...renato-bohler:zoom-step

With this code, it is possible to adjust sensitivity (by increasing/decreasing `zoomStep`) and zoom across browsers feels similar:

![zoom between Chrome and Firefox](https://i.imgur.com/s6lgXOr.gif)

What do you think @dylanvorster? Is this worth a PR or something?

**Comment by JeremyRubin** [comment] 2020-01-08 18:56
Looks great! My earlier search didn't turn up #360, thanks so much for your responsiveness!

I wonder if it's possible to auto-detect the zoom settings?

**Comment by pierre-moire** [comment] 2020-01-10 11:52
I am closing the ticket as duplicate of #360 . Can you keep on commenting there please?

**Closed by pierre-moire** 2020-01-10 11:52 UTC
