### ISSUE TITLE
Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by gthx** [projectstorm/react-diagrams#497] opened 2019-12-03 15:43 UTC
Serialization doesn't seem to work with Labels. Easiest repro is to call `link1.addLabel('label')` in `demos/demo-serializing` https://github.com/projectstorm/react-diagrams/blob/master/packages/diagrams-demo-gallery/demos/demo-serializing/index.tsx#L27-L28

I was able to track down the issue to https://github.com/projectstorm/react-diagrams/blob/master/packages/react-diagrams-core/src/entities/link/LinkWidget.tsx#L106-L114 where `LabelWidget` is rendered directly. Should it be using registered Label factory instead?

**Comment by gthx** [comment] 2019-12-03 18:43
I found a hack that works but I'm pretty sure the behavior with custom models is undefined. 
Replacing https://github.com/projectstorm/react-diagrams/blob/master/packages/react-diagrams-core/src/entities/label/LabelWidget.tsx#L90 with `const canvas = this.props.engine.getCanvas() || {offsetWidth:0, offsetHeight: 0};` works after repaint.

**Comment by JRMaitre** [comment] 2020-05-07 17:42
@gthx I was facing the same issue, and as a work around, I render the deserialized model after the engine has already been rendered once. It fixed the issue for me.

So in React I load the engine with an empty model and let React render it, then I added a useEffect to load the deserialized data on mount. Then the diagram renders as expected.

**Comment by actraiser** [comment] 2020-05-07 19:12
I believe the problem was fixed in release 6.1.0 from 2 weeks ago. I did not encounter any repaint issues with labels any more after upgrading.

Greets
-act

**Comment by vadimshvetsov** [comment] 2021-02-25 13:35
It still reproducible with v6.3.0

**Comment by GasparPontiroli9125** [comment] 2021-06-10 17:07
any update on this ?

Thanks.

**Comment by oussamajabnouni** [comment] 2021-06-18 09:29
Same issue here

**Closed** 2021-07-11 16:08 UTC
Labels: bug, needs investigation
