### ISSUE TITLE
Error thrown when running demo project

### ISSUE THREAD

**Issue by sikula** [projectstorm/react-diagrams#533] opened 2020-01-26 04:02 UTC
I tried to run the demo project, and I got an error saying "cannot use lexical scope value 'Polygon' before initialization'". When I commented out `import { Rectangle } from './Rectangle'` from `packages/geometry/src/Polygon` the error went away.  Not sure if this is intended or why this is happening.

**Comment by renato-bohler** [comment] 2020-01-26 15:01
Are you trying to run the `diagrams-demo-project`? Or is it the `diagrams-demo-gallery`?

What is your node version? Operating system? NPM or Yarn?

Both runs fine for me. I'm on Linux, node version 8.17.0, using yarn.

**Comment by sikula** [comment] 2020-01-26 20:43
1. I was running the `diagrams-demo-project`
2. Node version is `12.4.0`
3. Operating System is `Linux (Fedora)`
4. NPM version is `6.9.0`
5. Yarn version `1.16.0` (ran the code with yarn)

**Comment by jchen463** [comment] 2020-02-27 21:38
While trying to run diagrams-demo-project, I am also getting the same problem using:
Node: 12.9.1
OS: MacOS
npm: 6.13.5
yarn: 1.19.1

I am getting the same exception: "ReferenceError: Cannot access 'Polygon' before initialization"

**Comment by onefork** [comment] 2020-04-28 17:50
it's a circular dependency issue, potentially duplicate of #406 #437  

workaround is to run in the root

```
yarn build
```

_Originally posted by @stereobooster in https://github.com/projectstorm/react-diagrams/issues/406#issuecomment-534142125_

a good explanation and some solutions:
https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de

**Comment by dylanvorster** [comment] 2022-02-07 05:30
Running build in the root is not a workaround, but the correct way of building this library

**Closed by dylanvorster** 2022-02-07 05:30 UTC
