### ISSUE TITLE
Link path is not showing

### ISSUE THREAD

**Issue by lmoraobando** [projectstorm/react-diagrams#293] opened 2018-09-26 00:09 UTC
Hello guys!

I'm faced of this issue,
When I render the simple diagram the path of link is not showing,
I attach a gif,

https://drive.google.com/open?id=1NExH1wrOE_R6AXx_2dDFkhT4KLTI64V4

 on my code
` 
const { engine } = this.state;

        engine.installDefaultFactories();

        //2) setup the diagram model
        var model = new DiagramModel();

        //3-A) create a default node
        const node1 = new DefaultNodeModel("Node 1", "rgb(255,99,66)");
        let port1 = node1.addOutPort("Out");
        node1.setPosition(100, 100);

        //3-B) create another default node
        const node2 = new DefaultNodeModel("Node 2", "rgb(192,255,0)");
        let port2 = node2.addInPort("In");
        node2.setPosition(400, 100);

        // link the ports
        let link1 = port1.link(port2);
       // (link1 as DefaultLinkModel).addLabel("Hello World!");

        //4) add the models to the root graph
        model.addAll(node1, node2, link1);

        //5) load model into engine
        engine.setDiagramModel(model);

        this.setState({
            diagramEngine: engine,
        });`

**Comment by gydroperit** [comment] 2018-09-27 10:01
Because link has white color by default

**Comment by lmoraobando** [comment] 2018-09-27 15:07
That was the first thing I checked.
if you see the follow image with gray backgrond color , seems that path lost the relation between the nodes

![image](https://user-images.githubusercontent.com/11163835/46155514-b96fcd00-c234-11e8-966b-6d91928250c9.png)

**Comment by djacobsohn** [comment] 2018-10-07 14:00
Same issue... When connecting 2 nodes I can see the white line, but when I let the mouse button go the line becomes invisible. I can move the Nodes and it looks like the line is gone but when I hover in between the 2 nodes the line becomes visible again, but moving my cursor and it becomes invisible again.

**Comment by joeyparis** [comment] 2018-12-03 20:55
I am having the same problem. The path is completely removed from the `srd-link-layer` for me

**Comment by chidionuekwusi** [comment] 2019-01-07 21:33
Any luck with this ?. I'm experiencing the same issue.

**Comment by marcandreh** [comment] 2019-02-07 16:20
I experienced the same issue (paths dangling in the upper left corner).

I could fix the issue by creating my `DiagramModel` only when the`<DiagramWidget />` is truly visible (and not hidden by `position: hidden` for example). It seems like the `<DiagramWidget />` has to be visible to calculate its link paths correctly.

In my case a tabbed view created and prerendered all its tabs, so the model was created before its `<DiagramWidget />` was visible once. In your case the modal dialog is see in your screenshot might be the problem.

I hope i could help you.

**Comment by whistler** [comment] 2019-02-19 05:41
I faced the same issue, based on @marcandreh's comment, I figured hot reloading might be pre-rendering the diagram. Running webpack in production mode fixes it for me.

**Comment by dylanvorster** [comment] 2019-08-17 09:10
Should hopefully be fixed in the new version, cant really reproduce this behaviour

**Closed** 2019-08-17 09:09 UTC

**Comment by djacobsohn** [comment] 2019-08-17 22:00
Thx DylanExcellant library, keep up the good work.Kind RegardsDewald
-------- Original message --------From: Dylan Vorster <notifications@github.com> Date: 17/8/19  19:10  (GMT+10:00) To: projectstorm/react-diagrams <react-diagrams@noreply.github.com> Cc: djacobsohn <dewaldjacobsohn@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [projectstorm/react-diagrams] Link path is not showing (#293) Should hopefully be fixed in the new version, cant really reproduce this behaviour

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/projectstorm/react-diagrams/issues/293?email_source=notifications\u0026email_token=ACLTOOOABPWX3QVPYLFDFLDQE657LA5CNFSM4FXGXM6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4QHDFI#issuecomment-522219925",
"url": "https://github.com/projectstorm/react-diagrams/issues/293?email_source=notifications\u0026email_token=ACLTOOOABPWX3QVPYLFDFLDQE657LA5CNFSM4FXGXM6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4QHDFI#issuecomment-522219925",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by waelmas** [comment] 2020-09-15 11:31
I tried following the suggested fixes but nothing worked for me.

Here's what really fixed the issue for both the nodes and the elements not showing properly.

I removed the importing of `the storm-react-diagrams/dist/style.min.css`

and instead, I created a custom CSS file which is the above file with the following modifications (You can find it under `"node_modules/storm-react-diagrams/dist/"` **style.min.css**):


    .srd-diagram{position:unset;flex-grow:1;display:flex;cursor:move;overflow:visible}

(position to unset and overflow to visible)

    .srd-link-layer{position:unset; ...}

(position to unset)
