### ISSUE TITLE
Custom models help

### ISSUE THREAD

**Issue by deepak-workex** [projectstorm/react-diagrams#281] opened 2018-09-06 10:01 UTC
Hi, Has anyone set up the custom models given in the example diagrams ( create organisation, user etc )?
Can anyone share some light on this?
![example1](https://user-images.githubusercontent.com/43032380/45150627-e60e6700-b1e9-11e8-8ec1-027a460c6b39.jpg)
![example2](https://user-images.githubusercontent.com/43032380/45150628-e60e6700-b1e9-11e8-84bd-372f5906a407.jpg)

**Comment by RSayn** [comment] 2018-09-10 09:20
You should probably look at the [custom node demo](https://github.com/projectstorm/react-diagrams/tree/master/demos/demo-custom-node1): that should give you an idea of how you can implement custom nodes.
Basically you need to extend classes from the library according to what you need:

- AbstractFactory for factory class (you need this to tell the Diagram engine how to associate a Model class to the Widget you want!)
- NodeModel for the model: here you can change what data gets serialized, how ports are added, etc.
- BaseWidget for the node widgets.

You can have a look at the [defaults folder](https://github.com/projectstorm/react-diagrams/tree/master/src/defaults) to see how they are implemented and take it from there.

I got as far as to redefine a custom factory and model. From what I understand, widgets have some kind of classname-based logic to gather data for changes like moving nodes, and I wasn't able to make them work properly. For now I'm using the DefaultNodeWidget, since I was mostly interested in changing the model.

If you manage to add custom widgets, please share your experience :)

**Comment by PikkaPikkachu** [comment] 2019-06-20 11:49
I need help with the same- in particular with how to implement custom link widgets, if anyone can shed some light on that, then it would be really helpful.

**Comment by drummerjolev** [comment] 2019-07-15 11:18
Also need some help here. I'm getting "TypeError: Class extends value undefined is not a constructor or null" when attempting to implement the example Custom Node ([link to JSX example](https://github.com/rickhewes/jsx-storm-react-diagrams-demo)).

**Comment by matthax** [comment] 2019-07-25 20:30
I'm running into `TypeError: Class constructor  cannot be invoked without 'new'`

`engine.registerPortFactory(new JobPortFactory('job', config => new JobPortModel(config)));`

``` js
import { PortModel, AbstractPortFactory } from '@projectstorm/react-diagrams';

export class JobPortFactory extends AbstractPortFactory {

	constructor(type, cb) {
    super(type); // Error thrown here
		this.cb = cb;
  }
  /**
   *
   * @param {*} initialConfig Optional configuration object
   * @returns {PortModel} A new PortModel
   */
	getNewInstance(initialConfig = {}) {
		return this.cb(initialConfig);
	}
}
```
Not sure if it's related to your issue @drummerjolev but  would imagine that is likely the case.

**Comment by dylanvorster** [comment] 2019-07-25 20:34
@matthax @drummerjolev  your TSConfig options need to be:

```
"compilerOptions": {
		"declaration": false,
		"jsx": "react",
		"allowJs": true,
		"target": "es6",
		"moduleResolution": "node"
	},
```

**Comment by matthax** [comment] 2019-07-25 20:58
@dylanvorster I'm not using Typescript in my app, just transpiling with babel. Do I need to change my configuration to transpile this library as well?

**Comment by matthax** [comment] 2019-07-25 21:42
Thanks for the suggestion, it helped me track down the issue.

I'm using webpack + babel to transpile, in development I ignore everything in `node_modules` but still have my targets in the `.babelrc` file set like so:

``` json
            "targets": {
              "browsers": [
                "last 2 versions"
              ]
            }
```

The problem is this transpiles my local files to ES5, but not anything in node_modules. Thanks to [this answer on StackOverflow](https://stackoverflow.com/a/51860850/1641365) I realized this library isn't distributed already compiled to ES5.

The solution was, in development, simply to alter my targets in the `.babelrc` file:
``` json
            "targets": {
              "node": "6.5"
            }
```

**Comment by dylanvorster** [comment] 2019-08-11 14:38
Going to close this for now, as the entire project was vastly refactored and ES6 is now the default target. Furthermore there is a demo project that should get everyone up and running: https://github.com/projectstorm/react-diagrams/tree/master/packages/diagrams-demo-project

**Closed by dylanvorster** 2019-08-11 14:38 UTC

**Comment by serchduran** [comment] 2019-09-03 00:18
@dylanvorster I'm experimenting the same error in my App:

`TypeError: Class constructor cannot be invoked without 'new'`

the current repo example provided here works fine, but I'm getting the error when I try to use it in my app (even if I copy and paste the same demo example), I'm using the same TSConfig options you provided above, but it's still not working, do you know a workaround for this? Thanks, and awesome library!

**Comment by serchduran** [comment] 2019-09-04 00:50
nvm, I found the solution, I just included transpilation for the @projectstorm library and it worked, e.g in my `webpack.config.js`

 ```` 
...
// projectstorm is written for recent versions of the 
// node engine, so it will not work on older browsers 
// without transpilation 
path.resolve(__dirname, 'node_modules/@projectstorm') ], 
loader: require.resolve('babel-loader') }, 
...
````

**Comment by saschb2b** [comment] 2019-09-13 07:35
> @saschb2b of course man, this the entire block, let me know if you need more help
> 
> ```
> module: {
>       rules: [
>         {
>           test: /\.(js|ts|tsx)$/,
>           include: [
>             // projectstorm is written for recent versions of the
>             // node engine, so it will not work on older browsers
>             // without transpilation
>             path.resolve(__dirname, 'node_modules/@projectstorm')
>           ],
>           loader: require.resolve('babel-loader')
>         }        
>       ]
>     }
> ```
I always end up with `Uncaught TypeError: Cannot read property 'prototype' of undefined` as soon as I use any import of the packaes from `@projecstorm` (when applying this webpack rule)

![image](https://user-images.githubusercontent.com/2778161/64844766-ddc0e700-d608-11e9-928b-2639eac1ac09.png)

**Comment by serchduran** [comment] 2019-09-16 15:04
@saschb2b how are you importing it? could u provide an example?

I do it in this way

![image](https://user-images.githubusercontent.com/12452469/64969326-50300200-d869-11e9-9af9-2ff6461d0bda.png)

**Comment by saschb2b** [comment] 2019-09-16 15:49
@serchduran my packages and babelconfig weren't up to date. I've updated all relevant babel packages
![image](https://user-images.githubusercontent.com/2778161/64972688-fdc30580-d8a9-11e9-9a0e-023b1ff78c59.png)
![image](https://user-images.githubusercontent.com/2778161/64972709-0a475e00-d8aa-11e9-9b2f-84f4ca8e00a7.png)

It could be mainly the polyfills fault as it was a bet package at the time. The rest was "pretty" up to date though

and changed the babel config to target node with `preset-env`
![image](https://user-images.githubusercontent.com/2778161/64972780-2945f000-d8aa-11e9-847f-2f003d899593.png)

After that in combination with your webpack resolver I was able to use the package fully and build custom nodes

**Comment by codefromhimanshu** [comment] 2019-11-08 06:58
Getting this error while using the same code as in demo

```
Uncaught Error: Cannot find factory with type [undefined]
    at t.FactoryBank.getFactory (index.js:650)
    at t.DiagramEngine.getFactoryForNode (index.js:1234)
    at t.DiagramEngine.generateWidgetForNode (index.js:1256)
    at Object.children (index.js:770)
    at t.PeformanceWidget.render (index.js:1480)
    at finishClassComponent (react-dom.development.js:18461)
    at updateClassComponent (react-dom.development.js:18416)
    at beginWork$1 (react-dom.development.js:20145)
    at HTMLUnknownElement.callCallback (react-dom.development.js:337)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:386)
    at invokeGuardedCallback (react-dom.development.js:439)
    at beginWork$$1 (react-dom.development.js:25723)
    at performUnitOfWork (react-dom.development.js:24649)
    at workLoopSync (react-dom.development.js:24622)
    at performSyncWorkOnRoot (react-dom.development.js:24211)
    at react-dom.development.js:12263
    at unstable_runWithPriority (scheduler.development.js:821)
    at runWithPriority$2 (react-dom.development.js:12209)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12258)
    at flushSyncCallbackQueue (react-dom.development.js:12246)
    at discreteUpdates$1 (react-dom.development.js:24365)
    at discreteUpdates (react-dom.development.js:1442)
    at dispatchDiscreteEvent (react-dom.development.js:5917)
```

**Comment by kamleshgorasiya** [comment] 2020-03-25 19:57
> nvm, I found the solution, I just included transpilation for the @projectstorm library and it worked, e.g in my `webpack.config.js`
> 
> ```
> ...
> // projectstorm is written for recent versions of the 
> // node engine, so it will not work on older browsers 
> // without transpilation 
> path.resolve(__dirname, 'node_modules/@projectstorm') ], 
> loader: require.resolve('babel-loader') }, 
> ...
> ```
I have used [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate) as the foundation framework of my project  I am facing the same issue with react-diagram when I integrate it into the react-boilerplate framework.

Can you help me, where I need to put your solution babel.config.js and .eslintrc.js? 

Project configuration files

**babel.config.js**
=================================================
```
`module.exports = {
  sourceType: 'unambiguous',
  presets: [
    [
      '@babel/preset-env',
      {
        // targets: {
        //   node: 'current',
        // },
        exclude: [
          'babel-plugin-transform-classes',
          '@babel/plugin-transform-classes',
        ],
        modules: false,
      },
    ],
    '@babel/preset-react',
  ],
  plugins: [
    'styled-components',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-syntax-dynamic-import',
    ['import', { libraryName: 'antd', style: 'css' }],
  ],
  env: {
    production: {
      only: ['app'],
      plugins: [
        'lodash',
        'transform-react-remove-prop-types',
        '@babel/plugin-transform-react-inline-elements',
        '@babel/plugin-transform-react-constant-elements',
      ],
    },
    test: {
      plugins: [
        '@babel/plugin-transform-modules-commonjs',
        'dynamic-import-node',
      ],
    },
  },
};
`
```

**.eslintrc.js**
=====================================================
````
const fs = require('fs');
const path = require('path');

const prettierOptions = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, '.prettierrc'), 'utf8'),
);

module.exports = {
  parser: 'babel-eslint',
  extends: ['airbnb', 'prettier', 'prettier/react'],
  plugins: ['prettier', 'redux-saga', 'react', 'react-hooks', 'jsx-a11y'],
  env: {
    jest: true,
    browser: true,
    node: true,
    es6: true,
  },
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  rules: {
    'prettier/prettier': ['error', prettierOptions],
    'arrow-body-style': [2, 'as-needed'],
    'class-methods-use-this': 0,
    'import/imports-first': 0,
    'import/newline-after-import': 0,
    'import/no-dynamic-require': 0,
    'import/no-extraneous-dependencies': 0,
    'import/no-named-as-default': 0,
    'import/no-unresolved': 2,
    'import/no-webpack-loader-syntax': 0,
    'import/prefer-default-export': 0,
    indent: [
      2,
      2,
      {
        SwitchCase: 1,
      },
    ],
    'jsx-a11y/aria-props': 2,
    'jsx-a11y/heading-has-content': 0,
    'jsx-a11y/label-has-associated-control': [
      2,
      {
        // NOTE: If this error triggers, either disable it or add
        // your custom components, labels and attributes via these options
        // See https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-associated-control.md
        controlComponents: ['Input'],
      },
    ],
    'jsx-a11y/label-has-for': 0,
    'jsx-a11y/mouse-events-have-key-events': 2,
    'jsx-a11y/role-has-required-aria-props': 2,
    'jsx-a11y/role-supports-aria-props': 2,
    'max-len': 0,
    'newline-per-chained-call': 0,
    'no-confusing-arrow': 0,
    'no-console': 1,
    'no-unused-vars': 2,
    'no-use-before-define': 0,
    'prefer-template': 2,
    'react/destructuring-assignment': 0,
    'react-hooks/rules-of-hooks': 'error',
    'react/jsx-closing-tag-location': 0,
    'react/forbid-prop-types': 0,
    'react/jsx-first-prop-new-line': [2, 'multiline'],
    'react/jsx-filename-extension': 0,
    'react/jsx-no-target-blank': 0,
    'react/jsx-uses-vars': 2,
    'react/require-default-props': 0,
    'react/require-extension': 0,
    'react/self-closing-comp': 0,
    'react/sort-comp': 0,
    'redux-saga/no-yield-in-race': 2,
    'redux-saga/yield-effects': 2,
    'require-yield': 0,
  },
  settings: {
    'import/resolver': {
      webpack: {
        config: './internals/webpack/webpack.prod.babel.js',
      },
    },
  },
};
```
Where I need to put the that two-line in an above file some projectstrom can be transpile

**Comment by rzfzr** [comment] 2021-12-07 02:37
> Hi, Has anyone set up the custom models given in the example diagrams ( create organisation, user etc )? Can anyone share some light on this? ![example1](https://user-images.githubusercontent.com/43032380/45150627-e60e6700-b1e9-11e8-8ec1-027a460c6b39.jpg) ![example2](https://user-images.githubusercontent.com/43032380/45150628-e60e6700-b1e9-11e8-84bd-372f5906a407.jpg)

Is there any chance at all that @dylanvorster could share sample code for the form node widgets shown in theses images? I would be really grateful, and don't think I would be alone,,#911 #738
