### ISSUE TITLE
demo project wont run 

### ISSUE THREAD

**Issue by ghaith-bash-imam** [projectstorm/react-diagrams#430] opened 2019-09-14 01:42 UTC
`yarn`
then `yarn start `
open `localhost:9000`
`Polygon.ts:1 Uncaught ReferenceError: Cannot access 'Polygon' before initialization`

**Comment by dorrogeray** [comment] 2019-09-20 06:58
Duplicate of https://github.com/projectstorm/react-diagrams/issues/406

**Closed** 2019-12-30 20:35 UTC
