### ISSUE TITLE
'compilation' of undefined

### ISSUE THREAD

**Issue by Srikanththyagarajan** [projectstorm/react-diagrams#200] opened 2018-03-20 18:14 UTC
Im facing issue while trying to run the application using npm run storybook.,

C:\inetpub\wwwroot\react-diagrams-master\node_modules\webpack\lib\DefinePlugin.js:42
                compiler.hooks.compilation.tap(
                              ^

TypeError: Cannot read property 'compilation' of undefined
    at DefinePlugin.apply (C:\inetpub\wwwroot\react-diagrams-master\node_modules\webpack\lib\DefinePlugin.js:42:17)
    at Compiler.apply (C:\inetpub\wwwroot\react-diagrams-master\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (C:\inetpub\wwwroot\react-diagrams-master\node_modules\@storybook\react\node_modules\webpack\lib\webpack.js:33:19)
    at exports.default (C:\inetpub\wwwroot\react-diagrams-master\node_modules\@storybook\react\dist\server\middleware.js:29:40)
    at Object.<anonymous> (C:\inetpub\wwwroot\react-diagrams-master\node_modules\@storybook\react\dist\server\index.js:153:34)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\inetpub\wwwroot\react-diagrams-master\node_modules\@storybook\react\bin\index.js:3:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

kindly can anyone assist me

**Comment by dylanvorster** [comment] 2018-03-21 13:14
Fixed in 5.1.1 turns out awesome-typescript-loader is not so awesome.... as it drops .d.ts files for some reason

**Closed by dylanvorster** 2018-03-21 13:14 UTC

**Comment by Srikanththyagarajan** [comment] 2018-03-21 17:53
when i change the version of awesome-typescript-loader to 5.1.1 it says the version is not available and i not finding any solution online to make the application run, is it possible to share any blog or fix code/plugin

**Comment by Srikanththyagarajan** [comment] 2018-03-21 17:57
Thanks for the updated version, i hope it works charm

**Comment by Srikanththyagarajan** [comment] 2018-03-21 18:28
Hi i just downloaded version 5.1.1 but still im getting the same error 
![compilationerror](https://user-images.githubusercontent.com/17152714/37729698-bc2fa12a-2d63-11e8-83fa-51a19951528b.PNG)

**Comment by dylanvorster** [comment] 2018-03-21 19:25
are you downloading 5.1.1 from npm or are you downloading it form git? When I clone this from git, run yarn install and then yarn run storybook, everything works fine. I think the issue is that you are using npm which is not respecting the yarn.lock file

**Comment by Srikanththyagarajan** [comment] 2018-03-22 04:46
I did the same downloaded from npm and did npm install

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Srikanththyagarajan** [comment] 2018-03-22 04:50
I think the issue is my end, so let me understand what's the issue is and then I'll sure comeback for your suggestion, Thanks Dylan
