### ISSUE TITLE
Getting NaN error when creating a custom model node / drawing a link

### ISSUE THREAD

**Issue by josephjesseyoung** [projectstorm/react-diagrams#324] opened 2019-02-21 08:27 UTC
Hello, I'm getting this NaN error whenever I try to create a node or link. The problem is that the error occurs randomly and it is hard to replicate consistently.

here are some error screenshot I'm getting

![screen shot 2019-02-21 at 15 18 51](https://user-images.githubusercontent.com/23491683/53154097-89aed080-35ec-11e9-854d-09dd1f26ec48.png)

**note**: I'm using my own node implementation from custom diamond node, so I'm not sure if this is related to the error above. Anyone have experienced this before? any help is appreciated!

**Comment by dacopan** [comment] 2019-07-27 16:50
i have same error

**Comment by dylanvorster** [comment] 2019-08-11 14:44
Going to close this as cannot reproduce, also the library was completely refactored

**Closed by dylanvorster** 2019-08-11 14:44 UTC
