### ISSUE TITLE
Minification Serialization Problem

### ISSUE THREAD

**Issue by brunoalano** [projectstorm/react-diagrams#63] opened 2017-06-28 17:29 UTC
When we are running the production build, which is minimized using Uglify, all class names are minified, meaning that when you serialize your diagram, the class is not found.

See: https://github.com/projectstorm/react-diagrams/blob/01485add5c2662a152fc8345f1f5696b273f0a3a/src/Common.ts#L30

**Comment by dylanvorster** [comment] 2017-06-28 17:46
try turning off name mangling for now, at some point we are going too use string based identifiers instead

**Comment by brunoalano** [comment] 2017-06-28 17:53
I did that. I will PR a solution later so that you don't need to write an array of exceptions of mangling names.

**Comment by dylanvorster** [comment] 2017-06-28 20:26
Duplicate of #53

**Closed by dylanvorster** 2017-06-28 20:26 UTC
Labels: duplicate
