### ISSUE TITLE
engine.maxNumberPointsPerLink seems broken

### ISSUE THREAD

**Issue by tomitrescak** [projectstorm/react-diagrams#155] opened 2018-01-30 09:17 UTC
Hi, I tried to set the "engine.maxNumberPointsPerLink" but I can add as many control points I like. 

Sorry to post so many issues ;(

**Comment by dylanvorster** [comment] 2018-03-02 17:39
the max points per link demo seems to work as intended... closing for now

**Closed by dylanvorster** 2018-03-02 17:39 UTC
Labels: bug, needs investigation
