### ISSUE TITLE
Is there any way to create small preview of diagram created ?

### ISSUE THREAD

**Issue by coolji** [projectstorm/react-diagrams#284] opened 2018-09-08 10:34 UTC
Hello,

is there any way to create a small preview of a diagram created in diagram widget so that I can see all the node at once in small preview and move the portion of the diagram programmatically.

Thank you.

**Comment by dylanvorster** [comment] 2019-08-11 14:18
This is essentially a duplicate of: https://github.com/projectstorm/react-diagrams/issues/375 (you were first though xD)

**Closed by dylanvorster** 2019-08-11 14:18 UTC
Labels: duplicate, feature request
