### ISSUE TITLE
Npm Registry install doesnt work anymore

### ISSUE THREAD

**Issue by PetrykowskiM** [projectstorm/react-diagrams#694] opened 2020-08-06 09:18 UTC
Hi,

unfortunately npm doesnt provide your code anymore. When trying to install we get the following error:

`error An unexpected error occurred: "https://registry.yarnpkg.com/@projectstorm%2freact-diagrams: Not found".`

The more detailed version here:
```
Yarn version: 
  1.17.3

Node version: 
  14.4.0

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/@projectstorm%2freact-diagrams: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:66830:18)
      at Request.self.callback (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:140464:22)
      at Request.emit (events.js:315:20)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:141436:10)
      at Request.emit (events.js:315:20)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:141358:12)
      at Object.onceWrapper (events.js:421:28)
      at IncomingMessage.emit (events.js:327:22)
      at endReadableNT (_stream_readable.js:1224:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

**Comment by d2askif** [comment] 2020-08-06 09:42
I hope this gets resolved soon. I m stuck :)

**Comment by mradziwo** [comment] 2020-08-06 09:59
Same for me

**Comment by alexandernst** [comment] 2020-08-08 14:41
This was caused by a temporal failure on NPM's registry. It should be fixed now.

**Closed** 2020-12-03 20:35 UTC
